# src/observability/correlation_logger.py
"""
Correlation-Aware Structured Logger for HackaVerse
====================================================
Every log entry carries trace_id, parent_trace_id, route, method, user_id,
and event_type for full replay-visible request lineage.

Trace Propagation:
    - trace_id: unique ID for this request (generated by TraceIdMiddleware)
    - parent_trace_id: trace_id from the upstream caller (frontend or TANTRA)
    - Together they form a directed trace lineage graph

Usage:
    from ..observability.correlation_logger import CorrelationLogger

    clog = CorrelationLogger.from_request(request)
    clog.info("submission_created", status=200, extra={"team_id": "t1"})
"""

import json
import logging
import time
from datetime import datetime, timezone
from typing import Any, Dict, Optional

from fastapi import Request

logger = logging.getLogger("hackaverse.correlation")


class CorrelationLogger:
    """Structured logger that injects trace context into every log entry."""

    __slots__ = ("trace_id", "parent_trace_id", "route", "method", "user_id", "_start_time")

    def __init__(
        self,
        trace_id: str = "hv-unknown",
        parent_trace_id: Optional[str] = None,
        route: str = "",
        method: str = "",
        user_id: str = "anonymous",
    ):
        self.trace_id = trace_id
        self.parent_trace_id = parent_trace_id
        self.route = route
        self.method = method
        self.user_id = user_id
        self._start_time = time.monotonic()

    @classmethod
    def from_request(cls, request: Request) -> "CorrelationLogger":
        """Build a CorrelationLogger from a FastAPI Request object."""
        trace_id = getattr(request.state, "trace_id", "hv-unknown")
        parent_trace_id = getattr(request.state, "parent_trace_id", None)
        user_id = getattr(request.state, "user_id", "anonymous")
        return cls(
            trace_id=trace_id,
            parent_trace_id=parent_trace_id,
            route=str(request.url.path),
            method=request.method,
            user_id=user_id,
        )

    def _build_entry(
        self,
        event_type: str,
        status: Optional[int] = None,
        extra: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        entry: Dict[str, Any] = {
            "trace_id": self.trace_id,
            "event_type": event_type,
            "route": self.route,
            "method": self.method,
            "user_id": self.user_id,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }
        # Include parent_trace_id when available for trace lineage
        if self.parent_trace_id:
            entry["parent_trace_id"] = self.parent_trace_id
        if status is not None:
            entry["status"] = status
        elapsed = time.monotonic() - self._start_time
        entry["elapsed_ms"] = round(elapsed * 1000, 2)
        if extra:
            entry["details"] = extra
        return entry

    def _log(
        self,
        level: int,
        event_type: str,
        status: Optional[int] = None,
        extra: Optional[Dict[str, Any]] = None,
    ):
        entry = self._build_entry(event_type, status, extra)
        logger.log(level, json.dumps(entry, default=str))

    # ---- public convenience methods ----

    def info(self, event_type: str, status: int = 200, extra: Optional[Dict[str, Any]] = None):
        self._log(logging.INFO, event_type, status, extra)

    def warning(self, event_type: str, status: int = 400, extra: Optional[Dict[str, Any]] = None):
        self._log(logging.WARNING, event_type, status, extra)

    def error(self, event_type: str, status: int = 500, extra: Optional[Dict[str, Any]] = None):
        self._log(logging.ERROR, event_type, status, extra)

    def request_started(self):
        """Log the start of a request lifecycle."""
        self._log(logging.INFO, "request_started")

    def request_completed(self, status: int):
        """Log the completion of a request lifecycle."""
        self._log(logging.INFO, "request_completed", status)

    def request_failed(self, status: int, error_code: str, message: str):
        """Log a failed request."""
        self._log(
            logging.ERROR,
            "request_failed",
            status,
            extra={"error_code": error_code, "message": message},
        )
