#!/usr/bin/env python3
"""
Seed Data Script for HackaVerse
Initializes database with test data after reset.

Passwords are NEVER hardcoded. Set SEED_*_PASSWORD in .env or let the script
generate strong random passwords (written to .seed_credentials.local).
"""

import os
import sys
from pathlib import Path
from datetime import datetime, timedelta
from dotenv import load_dotenv
from pymongo import MongoClient
import bcrypt
import secrets

# Load environment
env_path = Path(__file__).resolve().parent / ".env"
load_dotenv(dotenv_path=env_path, override=True)

MONGODB_URI = os.getenv("MONGODB_URI")
DB_NAME = os.getenv("BUCKET_DB_NAME", "hackaverse_db")
ENV_MODE = os.getenv("ENV", "development").lower()

WEAK_PASSWORDS = {
    "admin@123",
    "judge@123",
    "participant@123",
    "password",
    "123456",
    "change_me_in_production",
}

SEED_ACCOUNTS = [
    ("admin", "admin@hackaverse.com", "user_admin_001", "Admin User", "admin"),
    ("participant", "participant@hackaverse.com", "user_participant_001", "John Participant", "participant"),
    ("judge", "judge@hackaverse.com", "user_judge_001", "Jane Judge", "judge"),
]

if not MONGODB_URI:
    print("ERROR: MONGODB_URI not set in .env")
    sys.exit(1)

print(f"\n{'='*70}")
print(f"[SEED] Connecting to MongoDB: {DB_NAME}")
print(f"{'='*70}\n")

try:
    client = MongoClient(MONGODB_URI, serverSelectionTimeoutMS=5000)
    client.admin.command("ping")
    db = client[DB_NAME]
    print("Connected to MongoDB\n")
except Exception as e:
    print(f"Failed to connect: {e}")
    sys.exit(1)

COLLECTIONS = {
    "users": "users",
    "sessions": "sessions",
    "hackathons": "hackathons",
    "teams": "teams",
    "user_teams": "user_teams",
    "submissions": "submissions",
    "judges": "judges",
}


def hash_password(password: str) -> str:
    return bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")


def resolve_seed_password(role_key: str) -> str:
    """Resolve password from env or generate a strong random value."""
    env_key = f"SEED_{role_key.upper()}_PASSWORD"
    password = os.getenv(env_key, "").strip()
    if not password:
        password = secrets.token_urlsafe(18)
        print(f"[SEED] Generated random password for {role_key} ({env_key} not set)")
    if len(password) < 12:
        print(f"ERROR: {env_key} must be at least 12 characters")
        sys.exit(1)
    if password.lower() in WEAK_PASSWORDS:
        print(f"ERROR: {env_key} uses a known weak/default password. Choose a strong unique value.")
        sys.exit(1)
    if ENV_MODE == "production" and not os.getenv(env_key):
        print(f"ERROR: In production you must set {env_key} explicitly (no auto-generation).")
        sys.exit(1)
    return password


def write_credentials_file(credentials: dict) -> Path:
    out_path = Path(__file__).resolve().parent / ".seed_credentials.local"
    lines = [
        "# Auto-generated by seed_data.py — DO NOT COMMIT",
        f"# Created: {datetime.now().isoformat()}",
        "",
    ]
    for role, data in credentials.items():
        lines.append(f"{role}:")
        lines.append(f"  email: {data['email']}")
        lines.append(f"  password: {data['password']}")
        lines.append(f"  role: {data['role']}")
        lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return out_path


seed_passwords = {}
for role_key, email, user_id, name, role in SEED_ACCOUNTS:
    seed_passwords[role_key] = resolve_seed_password(role_key)

credentials_out = {}

# ============================================================================
# SEED DATA
# ============================================================================

print("[SEED] Creating collections...\n")

# 1. Admin User
print("[SEED] Creating admin user...")
admin_password = seed_passwords["admin"]
admin_user = {
    "user_id": "user_admin_001",
    "email": "admin@hackaverse.com",
    "name": "Admin User",
    "role": "admin",
    "password_hash": hash_password(admin_password),
    "profile_completion": 100,
    "skills": ["Python", "FastAPI", "MongoDB"],
    "bio": "System Administrator",
    "created_at": datetime.now().isoformat(),
    "updated_at": datetime.now().isoformat(),
}
db[COLLECTIONS["users"]].delete_one({"email": "admin@hackaverse.com"})
db[COLLECTIONS["users"]].insert_one(admin_user)
credentials_out["admin"] = {"email": admin_user["email"], "password": admin_password, "role": "admin"}
print(f"Admin user created: {admin_user['email']}\n")

# 2. Participant User
print("[SEED] Creating participant user...")
participant_password = seed_passwords["participant"]
participant_user = {
    "user_id": "user_participant_001",
    "email": "participant@hackaverse.com",
    "name": "John Participant",
    "role": "participant",
    "password_hash": hash_password(participant_password),
    "profile_completion": 50,
    "skills": ["JavaScript", "React", "Node.js"],
    "bio": "Full-stack developer",
    "created_at": datetime.now().isoformat(),
    "updated_at": datetime.now().isoformat(),
}
db[COLLECTIONS["users"]].delete_one({"email": "participant@hackaverse.com"})
db[COLLECTIONS["users"]].insert_one(participant_user)
credentials_out["participant"] = {
    "email": participant_user["email"],
    "password": participant_password,
    "role": "participant",
}
print(f"Participant user created: {participant_user['email']}\n")

# 3. Judge User
print("[SEED] Creating judge user...")
judge_password = seed_passwords["judge"]
judge_user = {
    "user_id": "user_judge_001",
    "email": "judge@hackaverse.com",
    "name": "Jane Judge",
    "role": "judge",
    "password_hash": hash_password(judge_password),
    "profile_completion": 75,
    "skills": ["AI", "ML", "Data Science"],
    "bio": "AI/ML Expert",
    "created_at": datetime.now().isoformat(),
    "updated_at": datetime.now().isoformat(),
}
db[COLLECTIONS["users"]].delete_one({"email": "judge@hackaverse.com"})
db[COLLECTIONS["users"]].insert_one(judge_user)
credentials_out["judge"] = {"email": judge_user["email"], "password": judge_password, "role": "judge"}
print(f"Judge user created: {judge_user['email']}\n")

# 3b. Judges collection record
print("[SEED] Creating judge profile record...")
judge_profile = {
    "user_id": "user_judge_001",
    "email": "judge@hackaverse.com",
    "name": "Jane Judge",
    "role": "judge",
    "status": "active",
    "hackathon_name": "HackaVerse 2025",
    "created_at": datetime.now(),
    "updated_at": datetime.now(),
}
db[COLLECTIONS["judges"]].delete_one({"email": "judge@hackaverse.com"})
db[COLLECTIONS["judges"]].insert_one(judge_profile)
print("Judge profile created in judges collection\n")

# 4. Hackathon
print("[SEED] Creating hackathon...")
hackathon_id = f"hack_{datetime.now().timestamp()}"
hackathon = {
    "id": hackathon_id,
    "name": "HackaVerse 2025",
    "description": "Build innovative solutions using AI and modern technologies",
    "start_date": (datetime.now() + timedelta(days=7)).isoformat(),
    "end_date": (datetime.now() + timedelta(days=9)).isoformat(),
    "min_team_size": 2,
    "max_team_size": 5,
    "status": "active",
    "track": "Open Innovation",
    "participant_count": 0,
    "created_at": datetime.now().isoformat(),
    "updated_at": datetime.now().isoformat(),
}
db[COLLECTIONS["hackathons"]].delete_one({"name": "HackaVerse 2025"})
db[COLLECTIONS["hackathons"]].insert_one(hackathon)
print(f"Hackathon created: {hackathon['name']}")
print(f"   ID: {hackathon_id}\n")

# 5. Team
print("[SEED] Creating team...")
team_id = f"team_{datetime.now().timestamp()}"
team = {
    "team_id": team_id,
    "hackathon_id": hackathon_id,
    "team_name": "Team Alpha",
    "project_title": "AI-Powered Chat Assistant",
    "leader_id": "user_participant_001",
    "members": ["user_participant_001"],
    "created_at": datetime.now().isoformat(),
    "updated_at": datetime.now().isoformat(),
}
db[COLLECTIONS["teams"]].delete_one({"team_name": "Team Alpha"})
db[COLLECTIONS["teams"]].insert_one(team)
print(f"Team created: {team['team_name']}")
print(f"   ID: {team_id}\n")

# 6. User-Team Mapping
print("[SEED] Creating user-team mapping...")
user_team = {
    "user_id": "user_participant_001",
    "team_id": team_id,
    "role": "leader",
    "joined_at": datetime.now().isoformat(),
}
db[COLLECTIONS["user_teams"]].delete_one({"user_id": "user_participant_001", "team_id": team_id})
db[COLLECTIONS["user_teams"]].insert_one(user_team)
print("User-team mapping created\n")

# 7. Submission
print("[SEED] Creating submission...")
submission_id = f"sub_{datetime.now().timestamp()}"
submission = {
    "submission_id": submission_id,
    "team_id": team_id,
    "hackathon_id": hackathon_id,
    "title": "AI Chat Assistant",
    "description": "An intelligent chatbot powered by GPT and custom training",
    "github_link": "https://github.com/example/ai-chat",
    "demo_link": "https://demo.example.com/ai-chat",
    "submitted_by": "user_participant_001",
    "submitted_at": datetime.now().isoformat(),
    "status": "submitted",
    "score": None,
    "created_at": datetime.now().isoformat(),
}
db[COLLECTIONS["submissions"]].delete_one({"team_id": team_id})
db[COLLECTIONS["submissions"]].insert_one(submission)
print(f"Submission created: {submission['title']}\n")

# ============================================================================
# VERIFICATION
# ============================================================================

print(f"\n{'='*70}")
print("[SEED] VERIFICATION")
print(f"{'='*70}\n")

print(f"Users: {db[COLLECTIONS['users']].count_documents({})}")
print(f"Hackathons: {db[COLLECTIONS['hackathons']].count_documents({})}")
print(f"Teams: {db[COLLECTIONS['teams']].count_documents({})}")
print(f"Submissions: {db[COLLECTIONS['submissions']].count_documents({})}\n")

creds_path = write_credentials_file(credentials_out)

print(f"{'='*70}")
print("[SEED] CREDENTIALS (saved to file — not printed to logs)")
print(f"{'='*70}")
print(f"  File: {creds_path}")
print("  Set SEED_ADMIN_PASSWORD / SEED_PARTICIPANT_PASSWORD / SEED_JUDGE_PASSWORD in .env to use fixed passwords.\n")

client.close()

print(f"{'='*70}")
print("SEED DATA CREATED SUCCESSFULLY")
print(f"{'='*70}\n")
